config/routes.rb
Rails.application.routes.draw do
  resources :retweets
  resources :favs
  resources :follows
  resources :tweets
  resources :profiles
  root to: 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'user_follow/:user_id' , to: "follows#user_follow"
  post 'user_unfollow/:user_id' , to: "follows#user_unfollow"

  post 'like_tweet/:tweet_id' , to: "favs#like_tweet"
  post 'unlike_tweet/:tweet_id' , to: "favs#unlike_tweet"

  get 'retweet_new/:tweet_id' , to: "retweets#retweet_new"

  post 'tweet_retweet/:tweet_id' , to: "tweets#tweet_retweet"

end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  before_action :set_fav, only: [:show, :edit, :update, :destroy]

  # GET /favs
  # GET /favs.json
  def index
    @favs = Fav.all
  end

  # GET /favs/1
  # GET /favs/1.json
  def show
  end

  # GET /favs/new
  def new
    @fav = Fav.new
  end

  # GET /favs/1/edit
  def edit
  end

  def like_tweet
    @fav = Fav.new(get_tweet_id)
    @fav.user = current_user
    @fav.save!

    @tweet = Tweet.find(get_tweet_id[:tweet_id])
    respond_to do |format|
      format.js
    end
  end

  def unlike_tweet
    current_user.favs.where(get_tweet_id).first.delete

    @tweet = Tweet.find(get_tweet_id[:tweet_id])

    respond_to do |format|
      format.js
    end
  end

  # POST /favs
  # POST /favs.json
  def create
    @fav = Fav.new(fav_params)

    respond_to do |format|
      if @fav.save
        format.html { redirect_to @fav, notice: 'Fav was successfully created.' }
        format.json { render :show, status: :created, location: @fav }
      else
        format.html { render :new }
        format.json { render json: @fav.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favs/1
  # PATCH/PUT /favs/1.json
  def update
    respond_to do |format|
      if @fav.update(fav_params)
        format.html { redirect_to @fav, notice: 'Fav was successfully updated.' }
        format.json { render :show, status: :ok, location: @fav }
      else
        format.html { render :edit }
        format.json { render json: @fav.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favs/1
  # DELETE /favs/1.json
  def destroy
    @fav.destroy
    respond_to do |format|
      format.html { redirect_to favs_url, notice: 'Fav was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fav
      @fav = Fav.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fav_params
      params.require(:fav).permit(:user_id, :tweet_id)
    end

    def get_tweet_id
      params.permit(:tweet_id)
    end
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/views/favs/_form.html.erb
<%= form_with(model: fav, local: true) do |form| %>
  <% if fav.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fav.errors.count, "error") %> prohibited this fav from being saved:</h2>

      <ul>
      <% fav.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :fav_user_id %>
  </div>

  <div class="field">
    <%= form.label :tweet_id %>
    <%= form.text_field :tweet_id, id: :fav_tweet_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favs/_like.html.erb
<%= form_for tweet, as: :post, url: "like_tweet/#{tweet.id}" , method: :POST , remote: true , :html => {class: ""  } do |f| %>
  <%= button_tag(type: "submit", class: "btn btn-primary btn-xs " , data: { }) do %>
     Like
  <% end %>
<% end %>

app/views/favs/_unlike.html.erb
<%= form_for tweet, as: :post, url: "unlike_tweet/#{tweet.id}" , method: :POST , remote: true , :html => {class: ""  } do |f| %>
  <%= button_tag(type: "submit", class: "btn btn-danger btn-xs " , data: { }) do %>
     UnLike
  <% end %>
<% end %>

app/views/favs/edit.html.erb
<h1>Editing Fav</h1>

<%= render 'form', fav: @fav %>

<%= link_to 'Show', @fav %> |
<%= link_to 'Back', favs_path %>

app/views/favs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favs.each do |fav| %>
      <tr>
        <td><%= fav.user %></td>
        <td><%= fav.tweet %></td>
        <td><%= link_to 'Show', fav %></td>
        <td><%= link_to 'Edit', edit_fav_path(fav) %></td>
        <td><%= link_to 'Destroy', fav, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fav', new_fav_path %>

app/views/favs/like_tweet.js.erb
$('#fav_sec_<%=@tweet.id%>').empty();
$('#fav_sec_<%=@tweet.id%>').append('<%= escape_javascript(render(:partial => "favs/unlike" , locals: {tweet: @tweet})) %>');

app/views/favs/new.html.erb
<h1>New Fav</h1>

<%= render 'form', fav: @fav %>

<%= link_to 'Back', favs_path %>

app/views/favs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @fav.user %>
</p>

<p>
  <strong>Tweet:</strong>
  <%= @fav.tweet %>
</p>

<%= link_to 'Edit', edit_fav_path(@fav) %> |
<%= link_to 'Back', favs_path %>

app/views/favs/unlike_tweet.js.erb
$('#fav_sec_<%=@tweet.id%>').empty();
$('#fav_sec_<%=@tweet.id%>').append('<%= escape_javascript(render(:partial => "favs/like" , locals: {tweet: @tweet})) %>');