config/routes.rb
Rails.application.routes.draw do
  resources :retweets
  resources :favs
  resources :follows
  resources :tweets
  resources :profiles
  root to: 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'user_follow/:user_id' , to: "follows#user_follow"
  post 'user_unfollow/:user_id' , to: "follows#user_unfollow"

  post 'like_tweet/:tweet_id' , to: "favs#like_tweet"
  post 'unlike_tweet/:tweet_id' , to: "favs#unlike_tweet"

  get 'retweet_new/:tweet_id' , to: "retweets#retweet_new"

  post 'tweet_retweet/:tweet_id' , to: "tweets#tweet_retweet"

end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # Post
  def user_follow

    @follow = Follow.new(get_user_id)
    @follow.profile = current_user.profile
    @follow.save!
    @user = User.find(get_user_id[:user_id])
    respond_to do |format|
      format.js
    end
  end

  def user_unfollow
    
    current_user.profile.follows.where(get_user_id).first.delete
    @user = User.find(get_user_id[:user_id])
    respond_to do |format|
      format.js
    end
  end

  # POST /follows
  # POST /follows.json
  def create
    @follow = Follow.new(get_user_id)

    respond_to do |format|
      if @follow.save
        format.html { redirect_to @follow, notice: 'Follow was successfully created.' }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1
  # PATCH/PUT /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to follows_url, notice: 'Follow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follow_params
      params.require(:follow).permit( :user_id)
    end

    def get_user_id
      params.permit(:user_id)
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<%= form_for user, as: :post, url: "user_follow/#{user.id}" , method: :POST , remote: true , :html => {class: "delete_lang"  } do |f| %>
  <%= button_tag(type: "submit", class: "btn btn-primary btn-xs " , data: { }) do %>
     Follow
  <% end %>
<% end %>

app/views/follows/_form.html.erb
<%= form_with(model: follow, local: true) do |form| %>
  <% if follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id, id: :follow_profile_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :follow_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/follows/_unfollow.html.erb
<%= form_for user, as: :post, url: "user_unfollow/#{user.id}" , method: :POST , remote: true , :html => {class: "delete_lang"  } do |f| %>
  <%= button_tag(type: "submit", class: "btn btn-danger btn-xs " , data: { }) do %>
     UnFollow
  <% end %>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Follows</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.profile %></td>
        <td><%= follow.user %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @follow.profile %>
</p>

<p>
  <strong>User:</strong>
  <%= @follow.user %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>

app/views/follows/user_follow.js.erb
$('#follow_sec_<%=@user.id%>').empty();
$('#follow_sec_<%=@user.id%>').append('<%= escape_javascript(render(:partial => "follows/unfollow" , locals: {user: @user})) %>');

app/views/follows/user_unfollow.js.erb
$('#follow_sec_<%=@user.id%>').empty();
$('#follow_sec_<%=@user.id%>').append('<%= escape_javascript(render(:partial => "follows/follow" , locals: {user: @user})) %>');